version: '3.8'

services:
  apscheduler-webui:
    build:
      context: ..
      dockerfile: ./Dockerfile
    container_name: apscheduler-webui
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ../logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  # Optional: If MongoDB is needed as job storage
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - DB
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=password

  # Optional: If Redis is needed as job storage
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"

# Optional: Define volumes for databases
# volumes:
#   mongodb_data:
#   redis_data: